library(knitr)
library(ggplot2)
library(plyr)
library(dplyr)
library(corrplot)
library(caret)
library(gridExtra)
library(scales)
install.packages('Rmisc')
library(Rmisc)
library(ggrepel)
library(randomForest)
install.packages('psych')
library(psych)
library(xgboost)

train <- read.csv("./input/train.csv", stringsAsFactors = FALSE)
test <- read.csv('./input/test.csv', stringsAsFactors = FALSE)
